In [2]:
import numpy as np
import pandas as pd

In [3]:
a3 = np.array([[[1, 2, 3],
                [4, 5, 6]],
               [[7, 8, 9],
                [10, 11, 12]],
               [[13, 14, 15],
                [16, 17, 18]]])

In [4]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

# DataTypes & Attributes

In [5]:
# NumPy's main data type is ndarray

a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [6]:
type(a1)

numpy.ndarray

In [7]:
a2 = np.array([[1,2,3.3],[2,5,6.5]])

a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
               [[10,11,12],
                [13,14,15],
                [16,17,18]]])

In [8]:
a2

array([[1. , 2. , 3.3],
       [2. , 5. , 6.5]])

In [9]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [10]:
a1.shape

(3,)

In [11]:
a2.shape

(2, 3)

In [12]:
a3.shape

(2, 3, 3)

In [13]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [14]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [15]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [16]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [17]:
# Create dataframe from a numpy array

a2

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  2.0  5.0  6.5

In [18]:
a2

array([[1. , 2. , 3.3],
       [2. , 5. , 6.5]])

In [19]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [20]:
sample_array.dtype

dtype('int64')

In [21]:
ones = np.ones((3,2,2))
ones

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [22]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [23]:
ones.dtype

dtype('float64')

In [24]:
type(ones)

numpy.ndarray

In [25]:
zeros = np.zeros(shape=(2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [27]:
random_array = np.random.randint(0,10, size=(3,5))
random_array

array([[0, 5, 9, 3, 8],
       [6, 5, 6, 8, 3],
       [5, 6, 7, 7, 9]])

In [28]:
random_array.size

15

In [29]:
random_array.shape

(3, 5)

In [30]:
np.random.random((5,3))

array([[0.81664535, 0.8604159 , 0.46241143],
       [0.21713096, 0.93282789, 0.22092409],
       [0.96929001, 0.10029114, 0.73166129],
       [0.71096711, 0.98395582, 0.61000035],
       [0.7015366 , 0.84090822, 0.89439695]])

In [31]:
np.random.random((5,3)).size

15

In [32]:
np.random.random((5,3)).shape

(5, 3)

In [33]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.4711442 , 0.83619605, 0.23877513],
       [0.66363395, 0.67537095, 0.40309355],
       [0.44829236, 0.23089847, 0.80902878],
       [0.03010941, 0.03281317, 0.97560933],
       [0.14835947, 0.91502224, 0.66322932]])

In [37]:
# Psedo random numbers
np.random.seed(seed=0)
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [38]:
np.random.seed(seed=7)
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [39]:
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.90959353, 0.21338535, 0.45212396],
       [0.93120602, 0.02489923, 0.60054892],
       [0.9501295 , 0.23030288, 0.54848992],
       [0.90912837, 0.13316945, 0.52341258],
       [0.75040986, 0.66901324, 0.46775286]])

In [36]:
random_array_4.shape

(5, 3)

## 3. Viewing arrays and matrices

In [40]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
a1

array([1, 2, 3])

In [42]:
a2

array([[1. , 2. , 3.3],
       [2. , 5. , 6.5]])

In [43]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [44]:
a1[0]

1

In [45]:
a2[0]

array([1. , 2. , 3.3])

In [46]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
a3.shape

(2, 3, 3)

In [48]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [49]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [50]:
a4 = np.random.randint(10, size=(2,3,4,5))

In [51]:
a4

array([[[[6, 7, 7, 9, 3],
         [0, 7, 7, 7, 0],
         [5, 4, 3, 1, 3],
         [1, 3, 4, 3, 1]],

        [[9, 5, 9, 1, 2],
         [3, 2, 2, 5, 7],
         [3, 0, 9, 9, 3],
         [4, 5, 3, 0, 4]],

        [[8, 6, 7, 2, 7],
         [3, 8, 6, 6, 5],
         [6, 5, 7, 1, 5],
         [4, 4, 9, 9, 0]]],


       [[[6, 2, 6, 8, 2],
         [4, 1, 6, 1, 5],
         [1, 6, 9, 8, 6],
         [5, 9, 7, 5, 4]],

        [[9, 6, 8, 1, 5],
         [5, 8, 3, 7, 7],
         [9, 4, 7, 5, 9],
         [6, 2, 0, 5, 3]],

        [[0, 5, 7, 1, 8],
         [4, 9, 0, 2, 0],
         [7, 6, 2, 9, 9],
         [5, 1, 0, 0, 9]]]])

In [52]:
a4.shape

(2, 3, 4, 5)

In [53]:
a4.ndim

4

In [56]:
# Get first 4 numbers of inner most array
a4[:,:,:,:2]

array([[[[6, 7],
         [0, 7],
         [5, 4],
         [1, 3]],

        [[9, 5],
         [3, 2],
         [3, 0],
         [4, 5]],

        [[8, 6],
         [3, 8],
         [6, 5],
         [4, 4]]],


       [[[6, 2],
         [4, 1],
         [1, 6],
         [5, 9]],

        [[9, 6],
         [5, 8],
         [9, 4],
         [6, 2]],

        [[0, 5],
         [4, 9],
         [7, 6],
         [5, 1]]]])